{
    'name' : 'Hospital Management',
    'version': '18.0.0.1',
    'category' : 'Hospital Management',
    'sequence':-100,
    'author': 'Master',
    'summary' : "Hospital Management System",
    'description': """Hospital Management System""",
    'depends': ['mail'],
    'data':[
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/female_patient_view.xml',
        'views/appointment_view.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license':'LGPL-3',
}